// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#ifndef _WLED_CONTROLLER_UI_H
#define _WLED_CONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void OpaOn_Animation(lv_obj_t * TargetObject, int delay);
void OpaOff_Animation(lv_obj_t * TargetObject, int delay);
void ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuOut_Animation(lv_obj_t * TargetObject, int delay);
void ScreenOut_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen_1_Print
void ui_Screen_1_Print_screen_init(void);
extern lv_obj_t * ui_Screen_1_Print;
extern lv_obj_t * ui_PanelHeader;
extern lv_obj_t * ui_MainContainer1;
extern lv_obj_t * ui_Office_Panel1;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Office_Label1;
void ui_event_Office_On_and_Off(lv_event_t * e);
extern lv_obj_t * ui_Office_On_and_Off;
extern lv_obj_t * ui_InputContainer1;
void ui_event_OfficeBrightness(lv_event_t * e);
extern lv_obj_t * ui_OfficeBrightness;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_icn_time_1_png);    // assets/icn_time_1.png
LV_IMG_DECLARE(ui_img_icn_time_2_png);    // assets/icn_time_2.png


LV_FONT_DECLARE(ui_font_Small_Font);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
