// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#include "ui_events.h"
#include "lvgl.h"
#include <esp_log.h>

static const char *TAG = "ui_events";

void turnOnLight(lv_event_t * e) {
    ESP_LOGI(TAG, "Turning on and off the light");
}


