// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Primary[1] = {0x382BF0};
const ui_theme_variable_t _ui_theme_alpha_Primary[1] = {255};

const ui_theme_variable_t _ui_theme_color_textColor[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_textColor[1] = {255};

const ui_theme_variable_t _ui_theme_color_CardBackground[1] = {0x212529};
const ui_theme_variable_t _ui_theme_alpha_CardBackground[1] = {255};

const ui_theme_variable_t _ui_theme_color_Secondary[1] = {0x3F3F3F};
const ui_theme_variable_t _ui_theme_alpha_Secondary[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

