// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#ifndef _WLED_CONTROLLER_UI_COMP_HOOK_H
#define _WLED_CONTROLLER_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Container4_create_hook(lv_obj_t * comp);
void ui_comp_MainContainer_create_hook(lv_obj_t * comp);
void ui_comp_PanelHeader_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
