// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#ifndef _UI_COMP_PANELHEADER_H
#define _UI_COMP_PANELHEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelHeader
#define UI_COMP_PANELHEADER_PANELHEADER 0
#define UI_COMP_PANELHEADER_LABEL_HEADER 1
#define UI_COMP_PANELHEADER_IMG_WIFI 2
#define _UI_COMP_PANELHEADER_NUM 3
lv_obj_t * ui_PanelHeader_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
