// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#ifndef _UI_COMP_CONTAINER4_H
#define _UI_COMP_CONTAINER4_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Container4
#define UI_COMP_CONTAINER4_CONTAINER4 0
#define UI_COMP_CONTAINER4_SLIDER2 1
#define UI_COMP_CONTAINER4_SWITCH1 2
#define _UI_COMP_CONTAINER4_NUM 3
lv_obj_t * ui_Container4_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
