// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#include "../ui.h"

void ui_comp_Container4_create_hook(lv_obj_t * comp)
{
}

void ui_comp_MainContainer_create_hook(lv_obj_t * comp)
{
}

void ui_comp_PanelHeader_create_hook(lv_obj_t * comp)
{
}
