// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#ifndef _UI_COMP_MAINCONTAINER_H
#define _UI_COMP_MAINCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MainContainer
#define UI_COMP_MAINCONTAINER_MAINCONTAINER 0
#define UI_COMP_MAINCONTAINER_OFFICE_PANEL 1
#define UI_COMP_MAINCONTAINER_OFFICE_PANEL_OFFICE_LABEL 2
#define UI_COMP_MAINCONTAINER_CONTAINER4 3
#define UI_COMP_MAINCONTAINER_CONTAINER4_SLIDER2 4
#define UI_COMP_MAINCONTAINER_CONTAINER4_SWITCH1 5
#define UI_COMP_MAINCONTAINER_PANEL2 6
#define _UI_COMP_MAINCONTAINER_NUM 7
lv_obj_t * ui_MainContainer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
