// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#include "../ui.h"


// COMPONENT MainContainer

lv_obj_t * ui_MainContainer_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MainContainer;
    cui_MainContainer = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_MainContainer);
    lv_obj_set_width(cui_MainContainer, lv_pct(100));
    lv_obj_set_flex_grow(cui_MainContainer, 1);
    lv_obj_set_align(cui_MainContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_MainContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_MainContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(cui_MainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Office_Panel;
    cui_Office_Panel = lv_obj_create(cui_MainContainer);
    lv_obj_set_width(cui_Office_Panel, lv_pct(48));
    lv_obj_set_height(cui_Office_Panel, lv_pct(95));
    lv_obj_set_x(cui_Office_Panel, -237);
    lv_obj_set_y(cui_Office_Panel, 20);
    lv_obj_set_align(cui_Office_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Office_Panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Office_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Office_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Office_Panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBackground);
    ui_object_set_themeable_style_property(cui_Office_Panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBackground);
    lv_obj_set_style_border_side(cui_Office_Panel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Office_Label;
    cui_Office_Label = lv_label_create(cui_Office_Panel);
    lv_obj_set_width(cui_Office_Label, lv_pct(100));
    lv_obj_set_height(cui_Office_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Office_Label, 3);
    lv_obj_set_y(cui_Office_Label, -186);
    lv_obj_set_align(cui_Office_Label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Office_Label, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Office_Label, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(cui_Office_Label, "Printer Lights");
    lv_obj_set_style_text_color(cui_Office_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Office_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Office_Label, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container4;
    cui_Container4 = ui_Container4_create(cui_Office_Panel);
    lv_obj_set_x(cui_Container4, 4);
    lv_obj_set_y(cui_Container4, 0);

    lv_obj_t * cui_Panel2;
    cui_Panel2 = lv_obj_create(cui_MainContainer);
    lv_obj_set_width(cui_Panel2, lv_pct(48));
    lv_obj_set_height(cui_Panel2, lv_pct(95));
    lv_obj_set_x(cui_Panel2, -237);
    lv_obj_set_y(cui_Panel2, 20);
    lv_obj_set_align(cui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBackground);
    ui_object_set_themeable_style_property(cui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBackground);
    lv_obj_set_style_border_side(cui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAINCONTAINER_NUM);
    children[UI_COMP_MAINCONTAINER_MAINCONTAINER] = cui_MainContainer;
    children[UI_COMP_MAINCONTAINER_OFFICE_PANEL] = cui_Office_Panel;
    children[UI_COMP_MAINCONTAINER_OFFICE_PANEL_OFFICE_LABEL] = cui_Office_Label;
    children[UI_COMP_MAINCONTAINER_CONTAINER4] = cui_Container4;
    children[UI_COMP_MAINCONTAINER_CONTAINER4_SLIDER2] = ui_comp_get_child(cui_Container4, UI_COMP_CONTAINER4_SLIDER2);
    children[UI_COMP_MAINCONTAINER_CONTAINER4_SWITCH1] = ui_comp_get_child(cui_Container4, UI_COMP_CONTAINER4_SWITCH1);
    children[UI_COMP_MAINCONTAINER_PANEL2] = cui_Panel2;
    lv_obj_add_event_cb(cui_MainContainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MainContainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MainContainer_create_hook(cui_MainContainer);
    return cui_MainContainer;
}

