// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wled controller

#include "../ui.h"

void ui_Screen_1_Print_screen_init(void)
{
    ui_Screen_1_Print = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_Screen_1_Print, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_1_Print, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_Screen_1_Print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen_1_Print, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_1_Print, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen_1_Print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen_1_Print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHeader = ui_PanelHeader_create(ui_Screen_1_Print);
    lv_obj_set_x(ui_PanelHeader, 0);
    lv_obj_set_y(ui_PanelHeader, 0);



    ui_MainContainer1 = lv_obj_create(ui_Screen_1_Print);
    lv_obj_remove_style_all(ui_MainContainer1);
    lv_obj_set_width(ui_MainContainer1, lv_pct(100));
    lv_obj_set_flex_grow(ui_MainContainer1, 1);
    lv_obj_set_align(ui_MainContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MainContainer1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_MainContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Office_Panel1 = lv_obj_create(ui_MainContainer1);
    lv_obj_set_width(ui_Office_Panel1, lv_pct(48));
    lv_obj_set_height(ui_Office_Panel1, lv_pct(95));
    lv_obj_set_x(ui_Office_Panel1, -237);
    lv_obj_set_y(ui_Office_Panel1, 20);
    lv_obj_set_align(ui_Office_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Office_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Office_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Office_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Office_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBackground);
    ui_object_set_themeable_style_property(ui_Office_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBackground);
    lv_obj_set_style_border_side(ui_Office_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header = lv_obj_create(ui_Office_Panel1);
    lv_obj_remove_style_all(ui_Header);
    lv_obj_set_width(ui_Header, lv_pct(100));
    lv_obj_set_height(ui_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Header, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Header, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Header, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Office_Label1 = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Office_Label1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Office_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Office_Label1, 3);
    lv_obj_set_y(ui_Office_Label1, -186);
    lv_obj_set_align(ui_Office_Label1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Office_Label1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Office_Label1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Office_Label1, "Printer Lights");
    lv_obj_set_style_text_color(ui_Office_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Office_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Office_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Office_On_and_Off = lv_switch_create(ui_Header);
    lv_obj_set_width(ui_Office_On_and_Off, 50);
    lv_obj_set_height(ui_Office_On_and_Off, 25);
    lv_obj_set_x(ui_Office_On_and_Off, -118);
    lv_obj_set_y(ui_Office_On_and_Off, -6);
    lv_obj_set_align(ui_Office_On_and_Off, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Office_On_and_Off, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Office_On_and_Off, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);

    ui_object_set_themeable_style_property(ui_Office_On_and_Off, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Secondary);
    ui_object_set_themeable_style_property(ui_Office_On_and_Off, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Secondary);

    ui_InputContainer1 = lv_obj_create(ui_Office_Panel1);
    lv_obj_remove_style_all(ui_InputContainer1);
    lv_obj_set_width(ui_InputContainer1, lv_pct(100));
    lv_obj_set_flex_grow(ui_InputContainer1, 1);
    lv_obj_set_x(ui_InputContainer1, 153);
    lv_obj_set_y(ui_InputContainer1, -129);
    lv_obj_set_align(ui_InputContainer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InputContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OfficeBrightness = lv_slider_create(ui_InputContainer1);
    lv_slider_set_range(ui_OfficeBrightness, 0, 255);
    lv_slider_set_value(ui_OfficeBrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_OfficeBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_OfficeBrightness, 255,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_OfficeBrightness, 10);
    lv_obj_set_height(ui_OfficeBrightness, 150);
    lv_obj_set_x(ui_OfficeBrightness, 131);
    lv_obj_set_y(ui_OfficeBrightness, -54);
    lv_obj_set_align(ui_OfficeBrightness, LV_ALIGN_CENTER);


    ui_Panel1 = lv_obj_create(ui_MainContainer1);
    lv_obj_set_width(ui_Panel1, lv_pct(48));
    lv_obj_set_height(ui_Panel1, lv_pct(95));
    lv_obj_set_x(ui_Panel1, -237);
    lv_obj_set_y(ui_Panel1, 20);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBackground);
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBackground);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Office_On_and_Off, ui_event_Office_On_and_Off, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OfficeBrightness, ui_event_OfficeBrightness, LV_EVENT_ALL, NULL);

}
